#application.yml中设置Spring.profiles.active=test就是说默认以test环境设置然后利用命令行来设置不同的各个环境的不同的内容java -jar 应用的jar包 --spring.profiles.active=prod
spring:
    profiles:
        active: test
    freemarker:
          cache: false
    datasource:
            driver-class-name: com.mysql.jdbc.Driver
            password: root
            url: jdbc:mysql://localhost:3306/test
            username: root
    redis:
            database: 0
            host: localhost
            password: ''
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            port: 6379
            timeout: 0


com:
    didispace:
        blog:
            desc: test
            name: test
            title: Spring Boot教程
            bignumber: ${random.long}
            number: ${random.int}
            test1: ${random.int(10)}
            test2: ${random.int[10,20]}
            value: ${random.value}





